# Generated by Django 4.0.2 on 2022-03-15 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='average',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
